<?php
// $Id$
/*
 * Markdown Editor
 * by Jakob Persson of NodeOne <jakob@nodeone.se>
 *
 * Provides a toolbar for writing Markdown syntax with BUEditor.
 *
 * Sponsored by
 *   NodeOne - www.nodeone.se
 *
 * TODO: POT file to be generated.
 */

/**
 * Implementation of hook_form_alter()
 */
function markdowneditor_form_alter(&$form, $form_state, $form_id) {
  // Update buttons when modules are enabled or disabled
	if ($form_id == 'system_modules') {
    $form['#submit'][] = '_markdowneditor_update_buttons';
  }
}

/**
 * Update button definitions.
 */
function _markdowneditor_update_buttons() {

  // Set up variables
  $path = drupal_get_path('module', 'markdowneditor');  
  $eid = variable_get('markdowneditor_bueditor_buttons_table_eid', false);
  	
	// Include button definitions
  require_once("$path/markdowneditor.buttons.inc");	

  // Calculate table content fingerprint and compare to stored copy
  // only update table if contents have changed
  $fprint = md5($js_helpPath . $js_imceURL . $js_cssPath .$js_addStyleSheet);
  
  if ($fprint != variable_get('markdowneditor_bueditor_buttons_table_content_fprint', null)) {
    
  	// Store new fingerprint
  	variable_set('markdowneditor_bueditor_buttons_table_content_fprint', $fprint); 
  	
  	// Update buttons
	  foreach ($mde_buttons as $button) {
	    db_query("UPDATE {bueditor_buttons} SET content = '%s' WHERE eid = %d AND icon = '%s'", $button[2], $button[0], $button[3]);
	  }
	    	
  } 
}